- name: "K8s Slave Configuration"
  hosts: tag_Node_Slave
  tasks:
        - name: "Installing Required Packages"
          package:
               name:
                - "docker"
                - "iproute-tc"
               state: present

        - name: "Creating Yum Repo For Kubeadm, Kubelet, and Kubectl"
          yum_repository:
               name: kubernetes
               description: "Kubernetes"
               baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
               gpgcheck: yes
               gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
               exclude: kubelet kubeadm kubectl

        - name: "Installing Kubeadm, Kubelet, and Kubectl"
          yum:
              name: [ 'kubectl', 'kubeadm', 'kubelet' ]
              state: present
              disable_excludes: kubernetes

        - name: "Starting Kubelet Service"
          service:
               name: "kubelet"
               state: started
               enabled: yes

        - name: "Copy Daemon file to change the Docker's cgroup Driver"
          copy:
             src: "daemon.json"
             dest: "/etc/docker/daemon.json"

        - name: "Starting Docker Service"
          service:
               name: "docker"
               state: started
               enabled: yes

        - name: "Copy Kernel setting file"
          copy:
             src: "k8s.conf"
             dest: "/etc/sysctl.d/k8s.conf"       

        - command: "sysctl --system"   

        - name: "Copying token to slave nodes"
          copy: 
             src: /tmp/token
             dest: /tmp/token

        - name: "Joining the cluster"
          shell: "bash /tmp/token"
          ignore_errors: True














